name: Test Job

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          echo "Running tests1..."
          exit 0
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          echo "Running tests2..."
          exit 1
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          echo "Running tests3..."
          exit 0

  notify-slack:
    runs-on: ubuntu-latest
    needs: job3
    if: ${{ always() && needs.job3.result == 'failure' || needs.job3.result == 'skipped' }}
    steps:
      - name: Slack Notification(failure)
        uses: ./.github/actions/notify-failure-to-slack
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: 'ほげほげジョブに失敗しました！'
      