name: Test Job

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          echo "Running tests1..."
          exit 0
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          echo "Running tests2..."
          exit 1
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          echo "Running tests3..."
          exit 0

  notify-slack:
    runs-on: ubuntu-latest
    needs: job3
    if: ${{ always() && needs.job3.result == 'failure' || needs.job3.result == 'skipped' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create JSON payload
        run: |
          echo '{
            "blocks": [
              {
                "type": "rich_text",
                "elements": [
                  {
                    "type": "rich_text_section",
                    "elements": [
                      {
                        "type": "emoji",
                        "text": "warning"
                      },
                      {
                        "type": "text",
                        "text": "Workflowに失敗しました！"
                      },
                      {
                        "type": "emoji",
                        "text": "warning"
                      }
                    ]
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|GitHub Actions>"
                }
              }
            ]
          }' > payload-slack-content.json
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload-file-path: './payload-slack-content.json'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      